[package]
name = "Stock-Exchange-Simulation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.9.0-alpha.1"
crossbeam-channel = "0.5.12"
scheduled-thread-pool = "0.2"
